### ISSUE TITLE
Index with pattern mongo error on 1.0.4-rc.0

### ISSUE THREAD

**Issue by fusepilot** [aldeed/meteor-collection2#189] opened 2015-03-06 17:40 UTC
Upgraded from meteor 1.0.3.2 to 1.0.4-rc.0.

````MongoError: Index with pattern: { emails.address: 1 } already exists with different options````

Relevant schema:

````
"emails.$.address":
    type: String
    regEx: SimpleSchema.RegEx.Email
````

**Comment by aldeed** [comment] 2015-03-06 17:42
Pretty sure this is a duplicate of #166. Need to look at supporting Mongo 2.6 better. I will try to do that within the next week.

**Closed by aldeed** 2015-03-06 17:42 UTC
